# ---------------------------------------------------------------------------- #
# Base Setup                                                                   #
# ---------------------------------------------------------------------------- #
stages:
  - bulild
  - deploy

before_script:
  - ./devops/python/setup_poetry.sh

cache:
  paths:
    - .cache/pypoetry

# ---------------------------------------------------------------------------- #
# Package                                                                      #
# ---------------------------------------------------------------------------- #
docs:bulild:py39:
  stage: bulild
  image: python:3.9
  script:
    - ./devops/python/setup_dependencies.sh
    - ./devops/python/build_docs_with_jupyterbook.sh
  artifacts:
    paths:
      - _build/
    expire_in: 1 week
  only:
    - master

# ---------------------------------------------------------------------------- #
# Release                                                                      #
# ---------------------------------------------------------------------------- #
# Gitlab requires the use of the name "pages" for the job in order to have
# Gitlab Pages working correctly.
# docs:deploy:py39:
pages:
  stage: deploy
  image: busybox:latest
  before_script:
    - echo "Doesn't need any setup"
  script:
    - ./devops/python/publish_docs_to_gitlab_pages.sh
  artifacts:
    paths:
      - public/
    expire_in: 1 week
  dependencies:
    - docs:bulild:py39
  only:
    - master
