repos:
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        language: system
        entry: poetry run jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-pyupgrade
      - id: nbqa-isort
      - id: nbqa-black
      - id: nbqa-flake8
      - id: nbqa-pydocstyle
      - id: nbqa
        entry: poetry run nbqa mypy --ignore-missing-imports
        name: nbqa-mypy
        alias: nbqa-mypy
        additional_dependencies: [mypy==1.3.0, types-requests==2.30.0.0]
      - id: nbqa
        entry: poetry run nbqa bandit
        name: nbqa-bandit
        alias: nbqa-bandit
        additional_dependencies: [bandit==1.7.4]
      - id: nbqa-pylint
        args: [--disable=import-error, --disable=pointless-statement, --disable=invalid-name, --disable=expression-not-assigned]
        exclude: ^.*\b(notebooks-to-refactor)\b.*$
