# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
title: New Relic SB SDK
author: Dynova Development Team
copyright: "2022 - 2024"
logo: https://github.com/dynovaio/open-source-office/blob/master/assets/dynova/dynova-logo-195x64.png?raw=true
only_build_toc_files: true
exclude_patterns:
  - .*
  - _build
  - _config.yml
  - _templates
  - .git
  - .github
  - .ipynb_checkpoints
  - .venv
  - .vscode
  - data
  - renv
  - src
launch_buttons:
  notebook_interface: "jupyterlab"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html

execute:
  timeout: 100
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/dynovaio/newrelic-sb-sdk-playground/ # Online location of your book
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: master # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: https://github.com/dynovaio/open-source-office/blob/master/assets/dynova/dynova-favicon-black.png?raw=true
  use_issues_button: true
  use_edit_page_button: true
  use_repository_button: true
  baseurl: https://dynovaio.github.io/newrelic-sb-sdk-playground

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

sphinx:
  config:
    html_theme: sphinx_book_theme
    html_extra_path: ["LICENSE.txt"]
