version: "3.8"

services:
    jupyter:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: registry.gitlab.com/softbutterfly/open-source/newrelic-playground:dev
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./:/app
            - jupyter-venv:/app/.venv
        networks:
            - jupyter-network
        ports:
            - 9999:9999

volumes:
    jupyter-venv:
        driver: local

networks:
    jupyter-network:
        driver: bridge